services:
  # Frontend Service
  front-end:
    build:
      context: .
      args:
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_DATABASE_URL: ${VITE_FIREBASE_DATABASE_URL}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_INTERVIEW_API_URL: ${VITE_INTERVIEW_API_URL}
        VITE_MAJOR_API_URL: ${VITE_MAJOR_API_URL}
        VITE_UNIVERSITY_API_URL: ${VITE_UNIVERSITY_API_URL}
        VITE_RAG_API_URL: ${VITE_RAG_API_URL}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_DATABASE_URL=${VITE_FIREBASE_DATABASE_URL}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_INTERVIEW_API_URL=${VITE_INTERVIEW_API_URL}
      - VITE_MAJOR_API_URL=${VITE_MAJOR_API_URL}
      - VITE_UNIVERSITY_API_URL=${VITE_UNIVERSITY_API_URL}
      - VITE_RAG_API_URL=${VITE_RAG_API_URL}

    env_file:
      - .env
    volumes:
      - frontend_logs:/var/log/nginx
    networks:
      - career_compass_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  frontend_logs:

networks:
  career_compass_network:
    driver: bridge
